export enum ActionTypes {
  ADD_PAYMENT = 'PAYMENT/ADD',
  GET_PAYMENT = 'PAYMENT/GET',
  ADD_TRANSACTION = 'TRANSACTIONS/ADD',
  GET_TRANSACTIONS = 'TRANSACTIONS/GET',
  EXTRACT_MONEY = 'TRANSACTIONS/EXTRACT'
}